<?php

/**
 * This php file is automatically generated by Skolenet
 * Model - Class: forbidden_word
 */

if (0 > version_compare(PHP_VERSION, '5'))
{ die('This file was generated for PHP 5'); }


require_once('generated/class.generated_forbidden_word.php');


class forbidden_word
     extends generated_forbidden_word
{

} /* end of class forbidden_word */
?>