<?php

/**
 * This php file is automatically generated by Skolenet
 * Model - Class: media_connection
 */

if (0 > version_compare(PHP_VERSION, '5'))
{ die('This file was generated for PHP 5'); }


require_once('generated/class.generated_media_connection.php');


class media_connection
     extends generated_media_connection
{

} /* end of class media_connection */
?>