<?php

/**
 * This php file is automatically generated by Skolenet
 * Model - Class: team_network_id
 */

if (0 > version_compare(PHP_VERSION, '5'))
{ die('This file was generated for PHP 5'); }


require_once('generated/class.generated_team_network_id.php');


class team_network_id
     extends generated_team_network_id
{

} /* end of class team_network_id */
?>