<?php

/**
 * This php file is automatically generated by Skolenet
 * Model - Class: address
 */

if (0 > version_compare(PHP_VERSION, '5'))
{ die('This file was generated for PHP 5'); }


require_once('generated/class.generated_address_list.php');


class address_list
     extends generated_address_list
{

    /**
     *
     * This is the load function of the class address
     * @author Bernd Schröder
     *
     */
    public function load()
    {
      $where_statement = 
//      WHERE XXX=?;
      "";
      return $this->list_load( $where_statement );
    }

} /* end of class address */
?>