<?php

/**
 * This php file is automatically generated by Skolenet
 * Model - Class: address
 */

if (0 > version_compare(PHP_VERSION, '5'))
{ die('This file was generated for PHP 5'); }


require_once('generated/class.generated_address.php');


class address
     extends generated_address
{

} /* end of class address */
?>