<?php

/**
 * This php file is automatically generated by Skolenet
 * Model - Class: media
 */

if (0 > version_compare(PHP_VERSION, '5'))
{ die('This file was generated for PHP 5'); }


require_once('generated/class.generated_media.php');


class media
     extends generated_media
{

} /* end of class media */
?>