<?php

/**
 * This php file is automatically generated by Skolenet
 * Model - Class: private_information
 */

if (0 > version_compare(PHP_VERSION, '5'))
{ die('This file was generated for PHP 5'); }


require_once('generated/class.generated_private_information.php');


class private_information
     extends generated_private_information
{

} /* end of class private_information */
?>