<?php

/**
 * This php file is automatically generated by Skolenet
 * Model - Class: control_time_table_item
 */

if (0 > version_compare(PHP_VERSION, '5'))
{ die('This file was generated for PHP 5'); }


require_once('generated/class.generated_control_time_table_item.php');


class control_time_table_item
     extends generated_control_time_table_item
{

} /* end of class control_time_table_item */
?>