<?php

/**
 * This php file is automatically generated by Skolenet
 * Model - Class: media_file
 */

if (0 > version_compare(PHP_VERSION, '5'))
{ die('This file was generated for PHP 5'); }


require_once('generated/class.generated_media_file.php');


class media_file
     extends generated_media_file
{

} /* end of class media_file */
?>