<?php

/**
 * This php file is automatically generated by Skolenet
 * Model - Class: media_file
 */

if (0 > version_compare(PHP_VERSION, '5'))
{ die('This file was generated for PHP 5'); }


require_once('generated/class.generated_media_file_list.php');


class media_file_list
     extends generated_media_file_list
{

    /**
     *
     * This is the load function of the class media_file
     * @author Bernd Schröder
     *
     */
    public function load()
    {
      $where_statement = 
//      WHERE XXX=?;
      "";
      return $this->list_load( $where_statement );
    }

} /* end of class media_file */
?>