<?php

/**
 * This php file is automatically generated by Skolenet
 * Model - Class: team_team
 */

if (0 > version_compare(PHP_VERSION, '5'))
{ die('This file was generated for PHP 5'); }


require_once('generated/class.generated_team_team_list.php');


class team_team_list
     extends generated_team_team_list
{

    /**
     *
     * This is the load function of the class team_team
     * @author Bernd Schröder
     *
     */
    public function load()
    {
      $where_statement = 
//      WHERE XXX=?;
      "";
      return $this->list_load( $where_statement );
    }

} /* end of class team_team */
?>