<?php

/**
 * This php file is automatically generated by Skolenet
 * Model - Class: message_media
 */

if (0 > version_compare(PHP_VERSION, '5'))
{ die('This file was generated for PHP 5'); }


require_once('generated/class.generated_message_media.php');


class message_media
     extends generated_message_media
{

} /* end of class message_media */
?>